name: arima
channels:
  - conda-forge
dependencies:
  - jupyterlab=3.2.4
  - jupyterlab-spellchecker=0.7.2
  - matplotlib=3.5.0
  - numpy=1.21.4
  - pandas=1.3.4
  - pip=21.0.1
  - python=3.8.12
  - scipy=1.7.3
  - seaborn=0.11.2
  - statsmodels=0.11.1
  - pip:
    - pmdarima==1.8.4
    - forecast-tools==0.1.6
